---
spring:
  application:
    name: goinmul-worker-local
  profiles: local
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:  

logging:
  config: classpath:logback-local.xml
  
privacy:
  crypto: 
    use: false

---
spring:
  application:
    name: goinmul-worker-dev
  profiles: dev

logging:
  config: classpath:logback-dev.xml

privacy:
  crypto:
    use: false